### ISSUE TITLE
Why are you lying about the game using Direct3D to render the game objects? It's just movie files.

### ISSUE THREAD

**Issue by xTrayambak** [xuancong84/ProjectDIVA#2]

**Comment by xuancong84** [comment]
I never say use Direct3D to draw game objects. The source code does contains Direct3D drawing, I remember it is either the Rubix cube emulator or the music tempo visualization that I planned to integrate into the game.

**Comment by xTrayambak** [comment]
> I never say use Direct3D to draw game objects. The source code does contains Direct3D drawing, I remember it is either the Rubix cube emulator or the music tempo visualization that I planned to integrate into the game.

Sorry then, but you should know that many people are copying your code and making garbage rip-offs of project diva and are also earning money off them.

**Comment by xuancong84** [comment]
@xTrayambak , oh, thanks for informing, is it? I stopped working on the project long time ago. This repo is only for legacy backup purpose. Are you sure theirs are based on my code?
